bitwarden/passwordless-server

src/Service/Storage/EF/EfTenantStorage.cs

DBContext requires a thread safe execution

Reduce Async

---

src/AdminConsole/Program.cs
src/AdminConsole/RoutingHelpers/LinkGenerator.cs

- Remove the need to build the provider by using ActivatorUtilites
- Update Program.cs

better linkgeneration

---

src/Api/Endpoints/Register.cs
src/Service/Fido2ServiceEndpoints.cs
src/Service/Models/RegisterSession.cs
src/Service/Models/RegisterToken.cs
src/Service/Storage/EF/EfTenantStorage.cs
src/Service/Storage/EF/NoOpStorage.cs
src/Service/Storage/ITenantStorage.cs
src/Service/Storage/Storage.cs

1. register/token - verify if aliases is available when creating the token
2. register/token -  Change token type to include aliases
3. register/begin - send the aliases in the session
4. reigser/complete - retrieve them and store them on register complete.

Move Alias creation to register/complete

---

src/Service/Fido2ServiceEndpoints.cs
src/Service/Helpers/UnknownCredentialException.cs
tests/Api.IntegrationTests/BasicTests.cs
tests/Api.IntegrationTests/CredentialsTest.cs
tests/Api.IntegrationTests/PublicSignInTests.cs
tests/Api.IntegrationTests/RegisterTokenTests.cs

- Introduce Common UnknownCredentialException to improve reporting
- Add tests
For reporting reasons it would be helpful to separate this exception into it's own type.
I've also added tests to confirm it's being caught and handled correctly.

Improve Unknown Credential Exception

---

src/AdminConsole/Services/Mail/FileMailProvider.cs
src/AdminConsole/appsettings.Development.json
src/Api/Helpers/AddDatabaseExtensionMethod.cs
src/Api/Helpers/FriendlyExceptionsMiddleware.cs
src/Api/Program.cs

- Make Developing a bit Easier
- Formatting
- Fixed https and port
- Added better mail UX
- Added experimental support for doing migrations in the API project

even easier development

---

src/AdminConsole/Pages/Account/Profile.cshtml
src/AdminConsole/Pages/App/Credentials/List.cshtml
src/AdminConsole/Pages/App/Credentials/User.cshtml
src/AdminConsole/Pages/Components/ManagePasskeys/Default.cshtml
src/AdminConsole/Pages/Organization/Admins.cshtml
src/AdminConsole/Pages/Organization/Overview.cshtml
src/AdminConsole/Pages/Shared/_Layout.cshtml
src/AdminConsole/Pages/Shared/_credentials.cshtml
src/AdminConsole/wwwroot/js/elements/local-time.mjs

Adds a `local-time` custom element for converting server time to the client's local time. 
```html
<local-time datetime="2011-10-10T14:48:00"></local-time>
```

[PAS-71] add local-time element

---

.github/workflows/_deploy.yml

Attempt to fix the _deploy.yml workflow after carefully reading through [Using inputs and secrets in a reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)
- **.github/workflows/_deploy.yml:** Specify the secrets used at the top of the workflow

Adding secret inputs to the _deploy workflow

---

src/AdminConsole/Migrations/Mssql/20230818131329_AlterTableOrganizations_AddColumnBecamePaidAt.Designer.cs
src/AdminConsole/Migrations/Mssql/20230818131329_AlterTableOrganizations_AddColumnBecamePaidAt.cs
src/AdminConsole/Migrations/Mssql/MssqlConsoleDbContextModelSnapshot.cs
src/AdminConsole/Migrations/Sqlite/20230818130514_AlterTableOrganizations_AddColumnBecamePaidAt.Designer.cs
src/AdminConsole/Migrations/Sqlite/20230818130514_AlterTableOrganizations_AddColumnBecamePaidAt.cs
src/AdminConsole/Models/Organization.cs
src/AdminConsole/Services/BillingService.cs

SQL script generated on the internal ticket.

Add field 'BecamePaidAt' for 'Organization' in 'AdminConsole'

---

src/AdminConsole/Pages/Organization/Settings.cshtml.cs

PAS159: Unintentionally causing application to crash when canceling subscription

---

src/AdminConsole/Pages/App/Onboarding/GetStarted.cshtml
src/AdminConsole/Pages/App/Onboarding/GetStarted.cshtml.cs

Show correct API URL when running locally

---

src/AdminConsole/AdminConsole.csproj
src/AdminConsole/Program.cs
src/Api/Program.cs

To avoid having to update env variables

Added DD version in code

---

src/AdminConsole/Pages/App/Logs/Log.cshtml
src/AdminConsole/Pages/Organization/Log.cshtml

- Added tailwind
- Moved Datetime to be first
- Removed ToLocalDatetime, it uses server side time, not relevant
- World war on formatting
- Updated OrgLogs with TW

Add tailwind to Audit Logs

---

src/AdminConsole/Pages/App/Logs/Log.cshtml
src/AdminConsole/Pages/Organization/Log.cshtml

Paging wasn't passing the values to the route parameters because the `asp-page` tag wasn't included. Cleaned up the razor page by using `asp-if` attribute.

Fixing Organization Logs Paging

---

src/Service/EventLog/EventFunctions.cs
src/Service/Fido2ServiceEndpoints.cs
src/Service/IFido2ServiceFactory.cs
tests/Service.Tests/Implementations/Fido2ServiceEndpointsTests.cs

Refactored Register User events (begin, completed, verified) to be extension methods.

Refactored Register User Events

---

src/AdminConsole/Pages/App/Logs/Log.cshtml
src/AdminConsole/Pages/Organization/Log.cshtml

Added a small description to log pages.

Added description to log pages.

---

CONTRIBUTING.md

Added a migrations section to explain how to apply database changes using EF Core.

Adding Migrations Section

---

src/Service/Fido2ServiceEndpoints.cs

https://w3c.github.io/webauthn/#sctn-authenticator-credential-properties-extension

Support "credProps" / "rk"

---

src/AdminConsole/HealthEndpoints.cs
src/Api/HealthChecks/VersionHealthCheck.cs
src/Common/Extensions/AssemblyExtensions.cs

Show informational version in health checks

Version checks

---

.github/workflows/main.yml
src/AdminConsole/Program.cs

Related to: https://github.com/passwordless/passwordless-server/pull/168#issuecomment-1787039519

Create `datadog.json` file

---

src/AdminConsole/Pages/App/Logs/Log.cshtml
src/AdminConsole/Pages/Organization/Log.cshtml
src/AdminConsole/Styles/tailwind.css
src/AdminConsole/wwwroot/css/tailwind.css

PAS209: More padding needed around pagination breadcrumbs

---

src/AdminConsole/Pages/Organization/Settings.cshtml

PAS200: Make delete organization instructions more clear.

---

src/Api/Endpoints/Register.cs
src/Api/Endpoints/Signin.cs
src/Service/Fido2ServiceEndpoints.cs
src/Service/TokenService.cs

https://bitwarden.atlassian.net/browse/PAS-222
https://bitwarden.atlassian.net/browse/PAS-220

Improve error handling in `/signin/verify`

---

src/AdminConsole/appsettings.json

@jonashendrickx This change make sense right?

Use correct value in store

---

src/Api/Endpoints/Register.cs
src/Api/Endpoints/Signin.cs
src/Api/Extensions/HttpRequestExtensions.cs
src/Common/EventLog/Enums/EventType.cs
src/Service/EventLog/Loggers/IEventLogger.cs
src/Service/Fido2ServiceEndpoints.cs
src/Service/IFido2Service.cs
src/Service/Models/RegisterToken.cs
tests/Service.Tests/Implementations/Fido2ServiceEndpointsTests.cs

JIRA: https://bitwarden.atlassian.net/browse/PAS-224?atlOrigin=eyJpIjoiOTczMDZjN2EwZmIyNDM2NDgyMGE5YzYwNWQzYzUwNmEiLCJwIjoiaiJ9
Request:
```
POST /signin/token
{
"userId": "user123"
}
```
Response:
```
{
"token": "verify_asdkasjkdlajscldjaslkdjckasljdc"
}
```

Add `/signin/token` to create a verify token without the client flow

---

.github/workflows/main.yml
README.md

Doesn't work currently because we need IT to add secrets

Add Codecov

---

src/Api/Endpoints/Signin.cs

https://bitwarden.atlassian.net/browse/PAS-245

Rename the `/signin/token` endpoint

---

.github/workflows/docker.yml

Reverts bitwarden/passwordless-server#274

Revert "Temp fix for the docker deployments"

---

src/Api/Endpoints/Signin.cs
src/Service/Fido2Service.cs
src/Service/IFido2Service.cs
src/Service/Models/SignInTokenRequest.cs
src/Service/Models/SigninTokenRequest.cs
src/Service/Storage/Ef/EfTenantStorage.cs
src/Service/Storage/Ef/ITenantStorage.cs
tests/Api.IntegrationTests/Endpoints/SignIn/SignInTests.cs
tests/Api.IntegrationTests/Helpers/User/UserHelpers.cs
tests/Api.IntegrationTests/Helpers/WebDriverFactory.cs

We needed to validate that the user exists before issuing a token for sign-in. This will check Aliases and Credentials.

Added user check for generate token endpoint.

---

src/AdminConsole/Pages/App/Settings/Settings.cshtml
src/AdminConsole/Pages/App/Settings/Settings.cshtml.cs
tests/Api.IntegrationTests/Endpoints/Credentials/CredentialsTests.cs

Fix Enable/Disable of the Manual Verification Token Endpoint

---

src/AdminConsole/Components/Pages/App/Reporting.razor
src/AdminConsole/Components/Pages/App/ReportingComponents/TotalCredentialsCountChart.razor
src/AdminConsole/Components/Pages/App/ReportingComponents/TotalUsersCountChart.razor
src/AdminConsole/Components/Shared/ApexCharts/Models/ApexChartOptions.cs
src/AdminConsole/Components/Shared/ApexCharts/Models/Chart.cs
src/AdminConsole/Components/Shared/ApexCharts/Models/NoData.cs

Show that 'No data is available' when less than x data points

---

src/AdminConsole/AdminConsole.csproj
src/AdminConsole/Helpers/UseCsp.cs
src/AdminConsole/Pages/Shared/_PasswordlessClientJs.cshtml
src/AdminConsole/package-lock.json
src/AdminConsole/package.json

Hardens the security further, so no other script can be injected.

Get Passwordless client library from NPM.

---

src/Api/Program.cs

This was accidentally deleted by @Tyrrrz in #392.

Add `ReportingBackgroundService` again.

---

pull_request_template.md

- Closes [PAS-378](https://bitwarden.atlassian.net/browse/PAS-378)
This is a new PR template that will help the team communicate changes to each other which speeds up the review process. 
My approach with this template is to make it easier for PR reviewers to understand better what they are reviewing and to promote "Shape" PR's to share architectural decisions. 
(screenshots would go here)
[PAS-378]: https://bitwarden.atlassian.net/browse/PAS-378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-378 | Create pull request template

---

.editorconfig
src/Api/Authorization/AuthenticationBuilderExtensions.cs
src/Api/Endpoints/Alias.cs
src/Api/Endpoints/Apps.cs
src/Api/Endpoints/Credentials.cs
src/Api/Endpoints/Events.cs
src/Api/Endpoints/Register.cs
src/Api/Endpoints/Signin.cs
src/Api/Helpers/FriendlyExceptionsMiddleware.cs
src/Service/Fido2Service.cs
src/Service/IFido2Service.cs
src/Service/MagicLinks/MagicLinkService.cs
src/Service/SharedManagementService.cs
src/Service/UserCredentialsService.cs
tests/Api.IntegrationTests/AuthorizationTests.cs
tests/Api.Tests/Endpoints/AppsEndpointsTests.cs
tests/Service.Tests/Implementations/Fido2ServiceTests.cs

as result of #141 I added 'Async' suffix to async methods
Closes #141

Add 'Async' suffix to async methods

---

.github/pull_request_template.md

- Closes [PAS-378](https://bitwarden.atlassian.net/browse/PAS-378)
* Moves `pull_request_template.md` -> `.github/pull_request_template.md`
* Adds spaces between sections
[PAS-378]: https://bitwarden.atlassian.net/browse/PAS-378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-378 | PR Template: change template dir and add spaces

---

src/AdminConsole/Pages/App/Onboarding/GetStarted.cshtml

Fixes wrong link to the JS docs

Get started, fixed link

---

src/AdminConsole/Pages/Account/UserOnboarding.cshtml

- Closes [PAS-382](https://bitwarden.atlassian.net/browse/PAS-382)
The user onboarding page is throwing an exception related to a `Razor component` being embedded in a `TagHelper`, so it cannot associate the thread with the `Dispatcher`. 
Need to remove the `TagHelper` the Razor Component is embedded in.
[PAS-382]: https://bitwarden.atlassian.net/browse/PAS-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-382 | Fix `/account/useronboarding`

---

src/AdminConsole/wwwroot/js/core.js

Fixes the error below when you're not logged in:
`core.js?v=Y2Ukb10JnKwKJwpf4tb-G6HzDJAN5zuJx9bGbFxOU4E:8 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener') at core.js?v=Y2Ukb10JnKwKJwpf4tb-G6HzDJAN5zuJx9bGbFxOU4E:8:16`
n/a
n/a

Element references may not exist when not logged in.

---

src/AdminConsole/Services/DataService.cs

It is faster to generate an update statement rather than retrieving the record.
n/a
n/a

Make onboarding cleanup faster

---

src/Api/Endpoints/Alias.cs
src/Api/Endpoints/Register.cs
src/Api/Endpoints/Signin.cs
src/Common/Validation/MaxLengthCollectionAttribute.cs
src/Common/Validation/RequiredCollectionAttribute.cs
src/Service/Fido2Service.cs
src/Service/MagicLinks/Models/SendMagicLinkRequest.cs
src/Service/Models/AliasPayload.cs
src/Service/Models/MagicLinkTokenRequest.cs
src/Service/Models/RegisterToken.cs
src/Service/Models/SigninTokenRequest.cs
tests/Api.IntegrationTests/Endpoints/Register/RegisterTokenTests.cs

Validation is currently a spaghetti nightmare that's all over the place. This moves certain validation to earlier to the controllers.
n/a

Refactor validation for registering tokens, setting alias and magic links

---

src/Api/Endpoints/Magic.cs

N/A
This reverts commit f18e81d65bb22eb64757ee33710dc31ee337a2d6.
Following internal discussion. Commit looks a bit weird due to a conflict (I think). But at least necessary adds are added.
* Reviewed the code
* Reviewed the PR

Revert "Temporarily disable rate limiting in magic links endpoint (#463)"

---

src/AdminConsole/Pages/Account/Magic.cshtml.cs
src/AdminConsole/Services/MagicLinks/MagicClient.cs
src/AdminConsole/Services/MagicLinks/MagicLinkBuilder.cs

- Contributes to [PAS-375](https://bitwarden.atlassian.net/browse/PAS-375)
Allows for the return url to be added to magic links emails.
Forgot to add the returnUrl to the Magic Link template generator.
- __ Validate that the return url is appropriately appended to the magic uri.
- __
[PAS-375]: https://bitwarden.atlassian.net/browse/PAS-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix-magic-link-redirect

---

src/Api/Endpoints/Users.cs

- Closes [PAS-202](https://bitwarden.atlassian.net/browse/PAS-XXX)
- __
- __

PAS-202 | OpenAPI: Users

---

src/Api/Endpoints/Events.cs
src/Api/Program.cs

Enhance documentation for event logging.
- __
- __

PAS-202 | OpenAPI: Event logging

---

src/Api/Endpoints/Signin.cs

OpenAPI descriptions for signin endpoints.
n/a
- __
- __

PAS-202 | OpenAPI: Signin

---

src/Api/Endpoints/Register.cs

- Closes [PAS-202](https://bitwarden.atlassian.net/browse/PAS-XXX)
Adds description for the registration endpoints.
n/a
- __
- __

PAS-202 | OpenAPI: Registration

---

src/Api/Endpoints/Authenticators.cs
src/Api/Program.cs
src/Api/wwwroot/openapi.css
src/Common/Models/Authenticators/ConfiguredAuthenticatorRequest.cs

Openapi fixes

---

src/Api/wwwroot/openapi.css

Make the paths smaller.
n/a
- __
- __

PAS-202 | Make paths smaller

---

src/AdminConsole/Components/Pages/App/Onboarding/GetStarted.razor

The playground link was broken. It looks like it wasn't working for quite a while.
n/a
n/a
- __
- __

Fix playground link

---

src/AdminConsole/Endpoints/ApplicationEndpoints.cs

Suggestion by @Tyrrrz to improve performance was actually much slower: https://github.com/bitwarden/passwordless-server/pull/518
n/a
| Method | Mean     | Error   | StdDev  | Gen0   | Gen1   | Allocated |
|------- |---------:|--------:|--------:|-------:|-------:|----------:|
| New    | 139.4 ns | 0.77 ns | 0.64 ns | 0.3068 | 0.0012 |    2568 B |
| Old    | 101.5 ns | 1.22 ns | 1.14 ns | 0.1013 |      - |     848 B |
The old one is the change I'd want to merge back into `main`.
- __
- __

Improve performance for downloading onboarding keys.

---

src/AdminConsole/Components/Layouts/NavMenu.razor
src/AdminConsole/Components/Layouts/NavMenuItem.razor

Refactors the navigation menu to use a NavigationMenuItem component.
n/a
n/a
- Tested locally
- n/a

NavMenu refactoring

---

src/AdminConsole/Pages/Error.cshtml.cs
src/AdminConsole/Program.cs
src/AdminConsole/RateLimiting/AddRateLimitingExtensions.cs
src/AdminConsole/Services/InvitationService.cs
src/Api/Program.cs
src/Api/RateLimiting/RateLimitingExtensions.cs

- Closes https://bitwarden.atlassian.net/browse/PAS-334
- __
- __

PAS-334 | Rate Limiting Fine Tuning/Follow Up

---

src/Api/OpenApi/Filters/AuthorizationOperationFilter.cs
src/Api/Program.cs

- Replace 'default' value with example.
- Disable 'try it out' to avoid abuse.
n/a
n/a
- __
- __

PAS-202 | Disable 'try it out'

---

src/AdminConsole/Services/MagicLinks/MagicClient.cs
src/Api/Endpoints/Magic.cs
tests/Api.IntegrationTests/Endpoints/App/AppTests.cs
tests/Api.IntegrationTests/Endpoints/Magic/MagicTests.cs

- Closes https://bitwarden.atlassian.net/browse/PAS-403
- __
- __

PAS-403 | Rename route `/magic-link` to `/magic-links` (plural)

---

src/AdminConsole/Pages/Organization/Overview.cshtml

Of the 'Feedback' tag helper, the link to billing is broken.
n/a
- __
- __

Fix upgrade prompt link

---

src/AdminConsole/Components/Pages/App/Onboarding/GetStarted.razor

- Closes [PAS-409](https://bitwarden.atlassian.net/browse/PAS-409)
Private key was being shown as a regular text field, but should have been a password field with the eye-button.
- __
- __
[PAS-409]: https://bitwarden.atlassian.net/browse/PAS-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-409 | Hide private key as a password field

---

src/AdminConsole/Components/Pages/App/Credentials/List.razor.cs
src/Service/Models/UserSummary.cs

- Closes [PAS-410](https://bitwarden.atlassian.net/browse/PAS-410)
Alias count was accidentally prepended by a dollar sign
- __
- __
[PAS-410]: https://bitwarden.atlassian.net/browse/PAS-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-410 | Don't prepend alias count with dollar sign

---

src/AdminConsole/Components/Pages/Organization/Admins.razor

-  Related to [PAS-419](https://bitwarden.atlassian.net/browse/PAS-419)
Changes placeholder text in admin email field from `OpenApiExample.com` to `example.org` for consistency
- Will validate on merge to `main`, but pretty low risk since it's a placeholder copy change
- N/A

Small change to placeholder text domain

---

src/AdminConsole/AdminConsole.csproj

- [CVE-2024-29992](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-29992)
n/a
n/a
n/a
- __
- __

CVE-2024-29992

---

src/Api/Endpoints/Alias.cs
src/Api/Endpoints/Credentials.cs
src/Api/Endpoints/Magic.cs
src/Api/Endpoints/Register.cs
src/Api/Endpoints/Signin.cs
src/Api/OpenApi/ExternalDocsAttribute.cs
src/Api/OpenApi/Filters/AuthorizationOperationFilter.cs
src/Api/OpenApi/Filters/ExtendedStatusDescriptionsOperationFilter.cs
src/Api/OpenApi/Filters/ExternalDocsOperationFilter.cs
src/Api/Program.cs

- Closes https://bitwarden.atlassian.net/browse/PAS-408
Adds `External Documentation` links to each operation in the OpenAPI that has the corresponding page in our docs. Also updates the default descriptions of returned status codes with the ones we use in [our docs](https://docs.passwordless.dev/guide/api.html#status-codes).
- __
- __

PAS-408 | Link endpoints to their docs

---

src/AdminConsole/Pages/Organization/Create.cshtml
src/AdminConsole/Pages/Organization/Create.cshtml.cs

This adds two new fields to the create form.
This adds to new fields to the create form.
- __
- __

Adding fields to sign in page

---

tests/Api.IntegrationTests/AuthorizationTests.cs
tests/Api.IntegrationTests/Endpoints/App/AppTests.cs
tests/Api.IntegrationTests/Endpoints/Authenticators/AuthenticatorsTests.cs
tests/Api.IntegrationTests/Endpoints/Credentials/CredentialsTests.cs
tests/Api.IntegrationTests/Endpoints/Events/EventsTests.cs
tests/Api.IntegrationTests/Endpoints/Magic/MagicTests.cs
tests/Api.IntegrationTests/Endpoints/Register/RegisterAttestationTests.cs
tests/Api.IntegrationTests/Endpoints/Register/RegisterTests.cs
tests/Api.IntegrationTests/Endpoints/Register/RegisterTokenTests.cs
tests/Api.IntegrationTests/Endpoints/SignIn/SignInTests.cs
tests/Api.IntegrationTests/Helpers/App/CreateAppHelpers.cs
tests/Api.IntegrationTests/Helpers/HttpClientTestExtensions.cs
tests/Api.IntegrationTests/Helpers/User/UserHelpers.cs
tests/Api.IntegrationTests/Middleware/AuthorizationIntegrationTests.cs
tests/Api.IntegrationTests/Middleware/RoutingIntegrationTests.cs

- Closes https://bitwarden.atlassian.net/browse/PAS-430
- __
- __

PAS-430 | Don't rely on the global seeded development data in tests

---

src/AdminConsole/Pages/Organization/Create.cshtml.cs
src/AdminConsole/Program.cs

- Closes [PAS-440](https://bitwarden.atlassian.net/browse/PAS-440)
This adds some more information to the datadog logs and writes out some request info in the event of an improper POST.
Added Ip, User, and UserAgent to all datadog logs via serilog.
Added Form to the log information on an improper submission be either hidden field or dupliate user.
- Was able to log in and use AdminConsole normally
- Form was correctly logged in the event of the duplicate submission
- Form was correctly logged in the event of an invalid submission
N/A
[PAS-440]: https://bitwarden.atlassian.net/browse/PAS-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

PAS440-enhanced-logging

---

src/AdminConsole/Program.cs

clean up logs

---

src/Service/MagicLinks/MagicLinkService.cs

- Closes [PAS-415](https://bitwarden.atlassian.net/browse/PAS-415)
updates wording and styles in the magic link email
[PAS-415]: https://bitwarden.atlassian.net/browse/PAS-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-415 | update styles in magic link email

---

src/Api/HealthChecks/HealthCheckBootstrap.cs

Healthcheck endpoints aren't resolving as expected. They appear to have been moved.
- __
- __

Fix healthcheck endpoints 1.0.74

---

src/Service/MagicLinks/MagicLinkService.cs

- Closes [PAS-415](https://bitwarden.atlassian.net/browse/PAS-415)
Removing extra " that was causing a malformed link.
Removed " and unneeded px.
- Tested with example app
- Tested by sending email to myself
[PAS-415]: https://bitwarden.atlassian.net/browse/PAS-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove extra "

---

src/AdminConsole/Components/Shared/Icons/MailIcon.razor
src/AdminConsole/Pages/Organization/Verify.cshtml
src/AdminConsole/Pages/Shared/Icons/Mail.cshtml

- Closes [PAS-428](https://bitwarden.atlassian.net/browse/PAS-428)
Elevates the Verify page to not look like it's still in the POC stage. 
| desktop    | mobile |
| -------- | ------- |
| <img width="1395" alt="Screenshot 2024-05-02 at 2 28 20 PM" src="https://github.com/bitwarden/passwordless-server/assets/14082576/fab44b62-633b-48dc-869b-555cb3a9eded">  | <img width="444" alt="Screenshot 2024-05-02 at 2 28 31 PM" src="https://github.com/bitwarden/passwordless-server/assets/14082576/2f3ee1b0-e9f0-4f02-82b4-619a3c237136">|
[PAS-428]: https://bitwarden.atlassian.net/browse/PAS-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-428 | add elements and styles to verify page

---

src/Api/OpenApi/OpenApiBootstrap.cs
src/Api/Program.cs

Extract the OpenAPI bootstrapping code from `Program.cs` to enhance readability of said file. No code modifications were made.
n/a
- __
- __

Refactor/Extract OpenApi bootstrapping from Program.cs

---

src/AdminConsole/Services/Mail/DefaultMailService.cs

- Closes [PAS-252](https://bitwarden.atlassian.net/browse/PAS-252)
- __
- __
[PAS-252]: https://bitwarden.atlassian.net/browse/PAS-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-252 | Fix typos and improve wording in app deletion emails

---

src/AdminConsole/Components/Layouts/ApplicationNavMenu.razor
src/AdminConsole/Components/Layouts/NavMenu.razor
tests/AdminConsole.Tests/Components/Shared/Layouts/ApplicationNavMenuTests.cs

- Closes [PAS-208](https://bitwarden.atlassian.net/browse/PAS-208)
- __
- __
[PAS-208]: https://bitwarden.atlassian.net/browse/PAS-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-208 | Hide app logs when the app is pending deletion

---

src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/AuthenticationConfiguration.razor

- Closes [PAS-501](https://bitwarden.atlassian.net/browse/PAS-501)
Opens docs in new tab.
Aded target to link.
- manually tested
[PAS-501]: https://bitwarden.atlassian.net/browse/PAS-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS501-auth-config-docs-new-tab

---

src/Api/Endpoints/AuthenticationConfiguration.cs

- Closes [PAS-299](https://bitwarden.atlassian.net/browse/PAS-299)
Fix up some open api wording
- Changes reflected.
- n/a
[PAS-299]: https://bitwarden.atlassian.net/browse/PAS-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix some wording

---

src/Service/Fido2Service.cs

- Closes [PAS-525](https://bitwarden.atlassian.net/browse/PAS-525)
The error messages are being swallowed by the server when a customer has their application configured incorrectly or is using incorrect parameters with for example the `origin` on Android or iOS. This makes the development experience unpleasant.
The `Fido2VerificationException` is now intercepted and rethrows a `ApiException` to return the proper HTTP status code to the client with a user-friendly error message generated by the `fido2-net-lib` library.
```
Fido2NetLib.Fido2VerificationException: Fully qualified origin https://demo.passwordless.dev of https://demo.passwordless.dev not equal to fully qualified original origin ios:bundle-id:Q6SZ37AHX7.com.8bit.bitwarden.passwordlessios (1)
at …
```

PAS-525 | Bubble up the Fido2VerificationException error messages

---

src/AdminConsole/Components/Pages/Billing/Manage.razor

- Closes [PAS-480](https://bitwarden.atlassian.net/browse/PAS-480)
- __
- __
[PAS-480]: https://bitwarden.atlassian.net/browse/PAS-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-480 | Open 'Pricing' page in new tab/window.

---

src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/AttestationSection.razor
src/AdminConsole/Pages/App/Settings/Settings.cshtml

- Closes [PAS-479](https://bitwarden.atlassian.net/browse/PAS-479)
Migrating 'Attestation' section for consistency to prevent any lifecycle issues during application settings page expansion.
- __
- __
[PAS-479]: https://bitwarden.atlassian.net/browse/PAS-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-479 | Migrate attestation section in application settings

---

src/AdminConsole/Components/Pages/Organization/SettingsComponents/SecurityComponent.razor

- Closes [PAS-539](https://bitwarden.atlassian.net/browse/PAS-539)
- __
- __
[PAS-539]: https://bitwarden.atlassian.net/browse/PAS-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-539 | Use gender neutral language

---

src/AdminConsole/Components/Pages/Organization/SettingsComponents/SecurityComponent.razor

Improves the text for enabling/disabling magic links for organizations.
- __
- __

Improve magic links text

---

src/Api/Endpoints/Signin.cs
src/Service/Models/SignInVerifyDTO.cs

- Fix the API documentation where an unused property is present.
- Request model is listed as a response model.
- __
- __

Fix API documentation

---

src/AdminConsole/Pages/Account/Login.cshtml.cs
src/AdminConsole/Pages/Organization/CreateApplication.cshtml.cs

Fixes broken links on the login page as well as a redirect to the billing management page.
- __
- __

Fix broken links

---

src/AdminConsole/AdminConsole.csproj
src/AdminConsole/Components/App.razor
src/AdminConsole/Components/Pages/Organization/Create.razor
src/AdminConsole/Components/Pages/Organization/Create.razor.css
src/AdminConsole/package-lock.json
src/AdminConsole/package.json

Blazor CSS isolation with Tailwind.
Benefits:
- Borrow component styling from Bitwarden.
- More easily reuse components in alternative products.
- Verified that styles contained were still applied after making the changes.
- __

PAS-548 | Blazor CSS Isolation with Tailwind

---

src/AdminConsole/Components/Pages/App/Settings/AuthenticationConfiguration/AuthenticationConfigurationForm.razor
src/AdminConsole/Components/Pages/App/Settings/AuthenticationConfiguration/AuthenticationConfigurationFormModel.cs
src/AdminConsole/Components/Pages/App/Settings/AuthenticationConfiguration/CredentialHintStringAttribute.cs
src/AdminConsole/Components/Pages/App/Settings/AuthenticationConfiguration/CredentialHintStringValidationAttribute.cs

- https://bitwarden.atlassian.net/browse/PAS-549
- https://bitwarden.atlassian.net/browse/PAS-550
- https://bitwarden.atlassian.net/browse/PAS-551
- __
- __

Fix defects related to Passkey 3.0 Hints

---

.github/workflows/main.yml

Internal change.
Adds conditionals to check for secret existence in workflows so they don't fail on forks.

Check for secrets before using them

---

src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/DeleteApplicationSection.razor
tests/AdminConsole.Tests/Components/Pages/App/Settings/SettingsComponents/DeleteApplicationSectionTests.cs

- Closes [PAS-503](https://bitwarden.atlassian.net/browse/PAS-503)
- __
- __
[PAS-503]: https://bitwarden.atlassian.net/browse/PAS-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-503 | Improve app delete section in settings

---

src/AdminConsole/Components/Pages/Organization/Create.razor

- Closes [PAS-548](https://bitwarden.atlassian.net/browse/PAS-548)
- __
- __
[PAS-548]: https://bitwarden.atlassian.net/browse/PAS-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-548 | Organization creation page should not render page title

---

src/AdminConsole/wwwroot/js/modal.mjs

- Closes [PAS-553](https://bitwarden.atlassian.net/browse/PAS-553)
Pressing 'ESC' should close modals when they are open.
- __
- __
[PAS-553]: https://bitwarden.atlassian.net/browse/PAS-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-553 | Pressing ESC should close modals

---

src/AdminConsole/Components/Pages/App/Settings/Settings.razor
src/AdminConsole/Components/Pages/App/Settings/Settings.razor.cs
tests/AdminConsole.Tests/Components/Pages/App/Settings/SettingsTests.cs

- Closes [PAS-510](https://bitwarden.atlassian.net/browse/PAS-510)
- __
- __
[PAS-510]: https://bitwarden.atlassian.net/browse/PAS-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-510 | Hide application settings sections when pending deletion

---

src/AdminConsole/Services/SharedStripeBillingService.cs

- Closes [PAS-478](https://bitwarden.atlassian.net/browse/PAS-478)
It will now first check Stripe for active subscription items due to a corrupted state. It would have been nice if we can record all webhooks and their processing state.
- __
- __
[PAS-478]: https://bitwarden.atlassian.net/browse/PAS-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-478 | Stripe subscriptions could end up in a corrupted state

---

src/AdminConsole/Components/Shared/Cards/Card.razor.css
src/AdminConsole/Components/Shared/Cards/CardDetailsProperty.razor.css
src/AdminConsole/Components/Shared/Cards/CardSummaryProperty.razor.css
src/AdminConsole/Components/Shared/Credentials.razor.css
src/AdminConsole/Styles/tailwind.css

Isolate CSS for cards & credential cards

---

src/AdminConsole/Pages/Index.cshtml.cs

Broken redirect for '/organization/overview'

---

src/AdminConsole/Components/Shared/Credentials.razor.cs

This code is no longer being referenced or executed anywhere as the Razor component is not embedded on any Razor page.
- __
- __

Credentials: Drop backwards compatibility support for Razor Pages

---

src/AdminConsole/Components/Pages/Organization/Verify.razor

- Closes [PAS-565](https://bitwarden.atlassian.net/browse/PAS-565)
- __
- __
[PAS-565]: https://bitwarden.atlassian.net/browse/PAS-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-565 | Unexpected page title on ``/organization/verify`

---

src/AdminConsole/Services/Mail/DefaultMailService.cs
src/Common/Services/Mail/MailMessage.cs

Fix sending e-mails without HTML body breaking AWS SES.

---

src/AdminConsole/Components/Shared/Credentials.razor
src/AdminConsole/Components/Shared/Credentials.razor.cs

- Closes [PAS-567](https://bitwarden.atlassian.net/browse/PAS-567)
- __
- __
[PAS-567]: https://bitwarden.atlassian.net/browse/PAS-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-567 | Cannot delete credentials when admin has multiple credentials

---

src/AdminConsole/AdminConsole.csproj
src/Api/Api.csproj

Bump Datadog to 2.58

---

src/AdminConsole/Pages/Organization/Join.cshtml.cs
src/AdminConsole/Pages/Organization/JoinBusy.cshtml
src/AdminConsole/Pages/Organization/JoinBusy.cshtml.cs

Fixing links and routes.
We moved some pages from Razor to Blazor and this broke some links that were being generated by UrlHelper.
- Manually tested appropriate routing
- n/a

link-fixing

---

src/AdminConsole/Services/Mail/DefaultMailService.cs

- Closes [PAS-571](https://bitwarden.atlassian.net/browse/PAS-571)
- __
- __
[PAS-571]: https://bitwarden.atlassian.net/browse/PAS-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAS-571 | Organization name not correctly interpolated

---

src/AdminConsole/AdminConsole.csproj
src/Api/Api.csproj

Update Datadog.Trace to 3.2.0

---

src/Api/OpenApi/Filters/AuthorizationOperationFilter.cs
src/Api/OpenApi/OpenApiBootstrap.cs

- Closes [PAS-580](https://bitwarden.atlassian.net/browse/PAS-580)
This change will benefit improved client code generated from the Open API schema we provide.
References the authentication scheme name for every request.
```json
"/magic-links/send": {
"post": {
"tags": [
"Magic Links"
],
"summary": "Sends an e-mail containing a magic link template allowing users to login.",
"externalDocs": {
"description": "External Documentation",
"url": "https://docs.passwordless.dev/guide/api.html#magic-links-send"
},
"requestBody": {
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/SendMagicLinkRequest"
}
}
},
"required": true
},
"responses": {
"400": {
"description": "🔴 Bad request, see problem details for more info.",
"content": {
"application/problem+json": {
"schema": { …
```

PAS-580 | Use OpenApiSecurityRequirement instead of headers for auth

---

src/AdminConsole/package-lock.json
src/AdminConsole/package.json

Upgrade JavaScript Client SDK

---

.github/workflows/main.yml

- Closes [BRE-505](https://bitwarden.atlassian.net/browse/BRE-505)
- __
- __
[BRE-505]: https://bitwarden.atlassian.net/browse/BRE-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BRE-505] Use GitHub token from KeyVault

---

.github/workflows/main.yml

Fixed workflow name

---

.github/workflows/main.yml

Update `main.yml` workflow to use GitHub App token for triggering deployment workflow.
- __
- __

Update main workflow to use GitHub App token for deployment

---

.github/workflows/main.yml

https://bitwarden.atlassian.net/browse/VULN-202
Remove the check for secrets. Replace with logic to identify if the code is running in a fork.
- Tested across multiple repositories for similar changes 
- Kept changes minimal and only to workflow files

Remove secret check for tests

---

src/AdminConsole/Components/Routes.razor

Remove FocusOnNavigate

---

src/AdminConsole/Components/Pages/App/Settings/ManageAuthenticators.razor
src/AdminConsole/Endpoints/ComplimentaryEndpoints.cs

Move to an API endpoint to solve connections
