bitwarden/passwordless-server

.github/workflows/test-and-format.yml, src/ApiHelpers/ApiHelpers.csproj, src/AspNetCore/AspNetCore.csproj, src/Sdk/Sdk.csproj, src/Service/Service.csproj
Pack and publish a version of the `Passwordless.AspNetCore` and `Passwordless.Net` packages on each run of CI that also includes branch name. This way you can target `<PackageReference Include="Passwordless.Net" Version="0.0.10-ci-main-*" />` if you want the latest from `main` or you can target your own feature branch.
=> Auto Pack and Publish Packages

src/AdminConsole/Db/AddDatabaseExtensionMethod.cs, src/AdminConsole/Db/MssqlConsoleDbContext.cs, src/AdminConsole/Db/SqliteConsoleDbContext.cs, src/AdminConsole/appsettings.Development.json, src/Api/Helpers/AddDatabaseExtensionMethod.cs, src/Api/appsettings.Development.json, tests/Api.IntegrationTests/TestWebApplicationFactory.cs
Two motivations:
* Simplify to only have one config value to decide connection string
* Bug: We didn't properly use our new values
=> Breaking change: Uses specific value for db connection string.

.github/workflows/_version.yml
Update `_version.yml` to correctly reset the patch version when either the major or minor version is manually updated in `Directory.Build.props`
A successful calculation can be seen here: https://github.com/joseph-flinn/passwordless-server/actions/runs/5719822083/job/15498519352
=> Fix patch version calculation

.github/workflows/_test.yml, tests/Api.IntegrationTests/Api.IntegrationTests.csproj, tests/Api.Tests/Api.Tests.csproj, tests/Common.Tests/Common.Tests.csproj, tests/Service.Tests/Service.Tests.csproj
Adds [GHATL](https://github.com/Tyrrrz/GitHubActionsTestLogger) for reporting test results.
~~I left in `dorny/test-reporter` as well, but it might be obsolete now. Let me know if you want me to keep it or remove it.~~ Removed it.
See also https://github.com/passwordless/passwordless-dotnet/pull/21
=> Use `GitHubActionsTestLogger`

src/AdminConsole/AdminConsole.csproj, src/AdminConsole/Configuration/PasswordlessClientOptions.cs, src/AdminConsole/Pages/Account/Login.cshtml, src/AdminConsole/Pages/Account/Profile.cshtml, src/AdminConsole/Pages/Account/UserOnboarding.cshtml, src/AdminConsole/Pages/App/Credentials/User.cshtml, src/AdminConsole/Pages/App/Playground/Client.cshtml, src/AdminConsole/Pages/App/Playground/NewAccount.cshtml, src/AdminConsole/Pages/Components/ManagePasskeys/Default.cshtml, src/AdminConsole/Pages/Shared/_Layout.cshtml, src/AdminConsole/Program.cs
We already inject PasswordlessOptions when bootstrapping the Passwordless SDK, it's pointless to have PasswordlessClientOptions.
=> Refactoring & cleanup of options pattern.

src/AdminConsole/AuditLog/AuditLogEventFunctions.cs, src/AdminConsole/Pages/Organization/Join.cshtml.cs, src/AdminConsole/Services/InvitationService.cs, src/Common/AuditLog/Enums/AuditEventType.cs
This includes two new events for organization audit logs. One is for when an expired invite is used and for when an admin has successfully joined the organziation.
=> Added Organization Audit Log Events for Admin Invites

src/AdminConsole/Pages/App/Onboarding/GetStarted.cshtml
These sections seem completely duplicate aside from the links at the bottom for the last two. So I've added them to the framework/language specific cards.
=> Duplicate front-end and back-end sections.

src/AdminConsole/Services/ApplicationDeletionBackgroundService.cs, src/AdminConsole/Services/PasswordlessManagementClient.cs
Currently, `ApplicationDeletionBackgroundService` was calling the wrong endpoint to delete the application in API. I fixed the url and also added a check in to provide additional logging when an application deletion failed during the API call.
=> Fix scheduled application deletion

src/AdminConsole/Pages/Organization/Verify.cshtml, src/AdminConsole/Pages/Organization/Verify.cshtml.cs, src/AdminConsole/Pages/Shared/_Layout.cshtml
This will add a 15 second reload to the /Organization/Verify page.
After the user has signed up for an account, we send them to /organization/verify/.  Here we will now refresh the page every 15 seconds and if they've clicked the link or are verified, it will redirect them to the /account/useronboarding page to set up their passkey.
=> Adding Reload and Redirect to Organization/Verify

src/AdminConsole/Pages/Organization/Verify.cshtml
Making the comment on `Verify.cshtml` a razor block comment. `//` inside of the `@section {}` block will only not show the `//`. The rest of the comment will still show. `@* *@` will work as a comment on a razor page.
=> Fixing Comment on Verify.cshtml

src/AdminConsole/Pages/App/Credentials/List.cshtml, src/AdminConsole/Pages/App/Credentials/User.cshtml, src/AdminConsole/Pages/Components/ManagePasskeys/Default.cshtml, src/AdminConsole/Pages/Organization/Admins.cshtml, src/AdminConsole/Pages/Organization/Overview.cshtml, src/AdminConsole/Pages/Shared/_Credentials.cshtml
Title says it all. Removing `.ToLocalTime()` from the model `DateTime` properties since we are using javascript to convert the values to the client's local time. 
By having `.ToLocalTime()` in the template, we were actually converting the `DateTime` to the server's local time.
=> Removing `.ToLocalTime()` from razor pages.

src/AdminConsole/Pages/Organization/Log.cshtml.cs
We should fix this properly possibly with infinite scroll/paging. And also try to avoid passing around organizationId.
=> Fix concurrency exception

src/Api/Endpoints/Events.cs, src/Service/EventLog/EventFunctions.cs, src/Service/Fido2ServiceEndpoints.cs, src/Service/UserCredentialsService.cs
Two issues being fixed here. `signInWithAlias`, `signInWithAutoFill`, and `signInWithDiscoverable` all sent UserId as null which was unexpected.  Added some null checking and better wording for sign in event.
There was also the same concurrency issue from EF when using the same context for multiple concurrent calls.
=> Event Logging Fixes

src/AdminConsole/EventLog/Loggers/IEventLogger.cs, src/AdminConsole/Helpers/ClaimsExtension.cs, src/AdminConsole/Helpers/LoginEndpointFilter.cs, src/AdminConsole/Program.cs, src/Common/EventLog/Enums/EventType.cs
This adds an event to the organization event log for a successful admin sign-in from passkey.  I used and endpoint filter off the `.MapPasswordless()` endpoint builder because we use the `Passwordless` nuget package for sign in to the admin console.  This way we can allow everything to be default out of the box.  If there's a better way to do this, let me know.
=> Add Event for successful admin sign-in

src/AdminConsole/EventLog/AddEventLoggingRegistration.cs, src/AdminConsole/EventLog/EventDeletionBackgroundWorker.cs, src/AdminConsole/EventLog/Loggers/EventLoggerEfReadStorage.cs, src/AdminConsole/EventLog/Loggers/InternalEventStorage.cs, src/Service/EventLog/AddEventLoggingRegistration.cs, src/Service/EventLog/EventDeletionBackgroundWorker.cs
This PR is two parts.
Part one is deleting expired application event logs from the database that are outside of that tenant's feature expiration record saved in the database.  This occurs as a background task in the API.
Part two is deleting expired organization event logs from the database that are outside of the global organization retention setting from the config.  I had to create another context (`InternalEventLogStorage`) to handle this due to the context factory changes.  This will occur outside the request scope in a background service.
=> Delete event logs outside of the retention period.

src/AdminConsole/Pages/App/Credentials/List.cshtml, src/AdminConsole/Pages/App/Credentials/User.cshtml, src/AdminConsole/Pages/App/Logs/Log.cshtml, src/AdminConsole/Pages/Components/ManagePasskeys/Default.cshtml, src/AdminConsole/Pages/Organization/Admins.cshtml, src/AdminConsole/Pages/Organization/Log.cshtml, src/AdminConsole/Pages/Organization/Overview.cshtml, src/AdminConsole/Pages/Shared/_Credentials.cshtml, src/AdminConsole/TagHelpers/LocalTime.cs
When removing `.ToLocalTime()` from razor pages, some mac browsers stopped being able to process the datetime string when calling `new Date()`.  Added `.ToString("O")` so it would format to ISO-8601 standard.
Also added `<local-time />` component to Log pages.
=> Dates Show as "Invalid Date"

src/AdminConsole/EventLog/DTOs/AuditLogResponses.cs, src/AdminConsole/Pages/App/Logs/Log.cshtml
There was a mismatch between the api name model and the resposne model. This will make them the same.
=> Fixing api key on app logs

.github/workflows/main.yml
As discussed with @abergs.
The original version also used a timestamp to order versions (higher timestamps would appear earlier), but it might not be relevant here as it is in `passwordless-dotnet`.
=> Use only hash as prerelease version suffix

.github/workflows/main.yml, src/AdminConsole/Program.cs, src/AdminConsole/datadog.json, src/Api/Program.cs, src/Api/datadog.json
We currently utilize DD for monitoring logs, traces, deployments etc.
A essential feature is the version-tagging offered by DataDog to discover regressions and perf differences between deployments. 
This PR tries to move the responsibility of providing the version value away from the environment variable `DD_VERSION` towards code configuration.
**Motivation:** Configuring the DD_VERSION environment variable makes deployment complex and brittle, and out of sync (Actual code version might not be same as ENV variable)
**Problem:** Configuring the Version this way does not work -- Data Dogs UI indicates we no longer provide a version together with the logs.
Note: We're using the Azure App Service DataDog Extension.
Note 2: We would like to move towards OpenTelemetry where possible.
=> Try to configure DD Version from code

.github/workflows/docker.yml
Currently, docker images are tagged as `ghcr.io/passwordless/image:tag`. This will break when we move from the `passwordless` org to `bitwarden`, since the namespace will be different. This change removes static references to the org name and replaces them with dynamic ones.
=> Make docker deployments repo-agnostic

src/Service/Fido2Service.cs, src/Service/Storage/Ef/EfTenantStorage.cs, src/Service/Storage/Ef/ITenantStorage.cs, tests/Api.IntegrationTests/Endpoints/SignIn/SignInTests.cs
This removes the existing user requirement from the `/signin/generate-token` endpoint as it unintentionally limited the use of the endpoint. With this in place, the token could not be issued to a user who had yet to create a passkey in the system. By removing the restriction we can allow that use case.
=> Removing existing user requirement

src/AdminConsole/Controller/ApplicationEndpoints.cs, src/AdminConsole/Pages/Organization/CreateApplication.cshtml, src/AdminConsole/Program.cs, src/AdminConsole/Services/PasswordlessManagement/IPasswordlessManagementClient.cs, src/AdminConsole/Services/PasswordlessManagement/PasswordlessManagementClient.cs, src/Api/Endpoints/Apps.cs, src/Api/Models/AppAvailable.cs, src/Common/Models/Apps/GetAppIdAvailabilityRequest.cs, src/Common/Models/Apps/GetAppIdAvailabilityResponse.cs, tests/Api.IntegrationTests/Endpoints/App/AppTests.cs
- Endpoint is now using management key
- Endpoint can no longer be called without authentication to avoid scanning maliciously.
- Admin console uses endpoint protected by session of logged in user using ASP.NET Identity.
- Endpoint moved to match other management key endpoints 'GET /admin/apps/{appId}/available'.
- We will validate appId length client side before considering to call back-end.
=> Protect the POST '/apps/available' endpoint.

src/AdminConsole/AdminConsole.csproj, src/AdminConsole/package-lock.json, src/AdminConsole/package.json, src/AdminConsole/yarn.lock
This PR changes the dotnetbuild to use npm ci so that the install is clean, without updating lock files.
This causes a dependency on npm > 10. Not sure if that needs to be documented:
* `nvm use node`
* `npm install -g npm`
This PR also removes the slow/needles use of npx.
=> Use npm ci

src/AdminConsole/Pages/Organization/CreateApplication.cshtml.cs, src/AdminConsole/Services/ApplicationService.cs, src/AdminConsole/Services/PasswordlessManagement/IPasswordlessManagementClient.cs, src/AdminConsole/Services/PasswordlessManagement/PasswordlessManagementClient.cs
PAS-314
Also renamed some methods to have the `Async` suffix for consistency with other methods, added `using` to make proper use of the `IDisposable` pattern, and some other minor corrections.
=> Add URL-encoding to `PasswordlessManagementClient`

src/Service/Migrations/Mssql/20240118190159_NormalizeNullability.Designer.cs, src/Service/Migrations/Mssql/20240118190159_NormalizeNullability.cs, src/Service/Migrations/Mssql/MsSqlContextModelSnapshot.cs, src/Service/Migrations/Sqlite/20240118190130_NormalizeNullability.Designer.cs, src/Service/Migrations/Sqlite/20240118190130_NormalizeNullability.cs
#340 fixed nullability annotations in database models, but didn't include migrations to normalize them in the database schema. This PR fixes that.
=> Normalize nullability in the database schema

src/AdminConsole/RateLimiting/AdminPageRateLimit.cs
Lowering this limit to 50 to reduce ability to send out spam emails.  This would cover the case of sending then canceling the same email address over and over again.  It takes roughly 5 requests for the steps of loading the page, sending the page, then canceling the invite.  So to limit to 10 per minute, we would set the request limit to 50.
=> Lowering Admin Page rate limit

renovate.json
This package has to be in-sync with the version of the agent we use in Azure, so we need to update it manually.
Docs reference: https://docs.renovatebot.com/configuration-options/#ignoredeps
Related: https://github.com/bitwarden/passwordless-server/pull/369
=> Ignore `Datadog.Trace` in Renovate updates

.github/workflows/main.yml
Renovate relies on these comments to match hashes to tags, but this action doesn't prepend tags with `v` like the other actions.
=> Fix pin reference for HTTP request action

src/AdminConsole/Pages/Organization/Admins.cshtml.cs, src/AdminConsole/RateLimiting/AdminPageRateLimit.cs, src/AdminConsole/Services/IInvitationService.cs, src/AdminConsole/Services/InvitationService.cs
Added some error messaging in the event a non-existent hash is passed in. Also, using the existing invite to cancel instead of passing the hashedcode through.
=> Using existing record to cancel invite

src/AdminConsole/Pages/App/Settings/Settings.cshtml, src/AdminConsole/Styles/tailwind.css
Added `inline-block` to `btn` so that buttons have the same uniform size.
Before:
After:
=> Fixed Attestation link size to match other "buttons"

src/AdminConsole/Pages/Organization/CreateApplication.cshtml
=> UI prompt does not make sense when no plans are shown

src/Service/Fido2Service.cs
When an allowlist is configured, we want to return a proper error message when registering a credential fails with attestation `none`.
=> Configuring allowlist should expect attestation to be used.

src/AdminConsole/AdminConsole.csproj, src/AdminConsole/appsettings.json, src/Api/Api.csproj, src/Api/appsettings.json
If the path contains `/health/`, we can exclude request logging when it is successful. We still want to capture failed requests.
=> Exclude health checks from event logging

src/Service/Migrations/Mssql/20240213130303_MagicLinkEmailQuota.cs, src/Service/Migrations/Sqlite/20240213130331_MagicLinkEmailQuota.cs
The initialization for the default values was left out in the last SQL Server and Sqlite migration. We can safely assume 10k MaxUsers means the `Trial` plan while all others are `Pro` or `Enterprise`.
=> Fix migration script for production

.editorconfig, global.json
- Bitwarden is also using `latestFeature` for an automatic rollover.
- If `latestMinor` is kept, we should disable `dotnet_diagnostic.IDE0005.severity`.
We could also consider looking into Matt Bischop's proposal to use a different solution: https://github.com/bitwarden/template/pull/14/files#diff-942a301e84bfe0b5304682d3ace46bcea39fd95bc4f6a600f64f1f2575fdf53f
Still working with Microsoft on resolving this.
Related:
- https://github.com/dotnet/roslyn/issues/72015
- https://github.com/dotnet/roslyn/issues/72160
- https://github.com/bitwarden/passwordless-server/actions/runs/7989471492/job/21816103177
=> .NET 8.0.2 `IDE0005` `dotnet format` issue

src/Service/MagicLinks/MagicLinkService.cs, src/Service/MagicLinks/Models/SendMagicLinkRequest.cs, src/Service/MagicLinks/Validation/MagicLinkUrlTemplateAttribute.cs, tests/Api.IntegrationTests/Endpoints/Magic/MagicTests.cs, tests/Api.IntegrationTests/Helpers/App/RequestHelpers.cs
Characters such as `<>`, `{}`, and `[]` are frequently escaped by frameworks. Switching from `<token>` to `$TOKEN` for the token template will hopefully help keep this feature painless.
=> PAS 371 - Change token template

src/AdminConsole/Pages/App/Settings/Settings.cshtml
Now that the Magic Links endpoint is enabled, we should allow devs to turn it off and on via settings for their application.
Screenshots:
- Before
- After
Testing:
- Made sure both MGAT and Magic links settings worked when toggling on and off the features.
=> Show Magic Link Setting

src/Service/SharedManagementService.cs, src/Service/Storage/Ef/EfTenantStorage.cs, tests/Service.Tests/Implementations/SharedManagementServiceTests.cs
Issue:
Currently, there is an issue with deleting the app due to some refactoring and scoping issues of the tenant storage.  This will fix the storage issues for now.  It uses the tenant factory to get an instance instead of the injected one. Later, we'll come back and finish swapping out the tenant factory with the tenant storage injected through DI.
Validation:
- I am now able to delete an application.
=> Fix app deletion

src/Service/Migrations/Mssql/20240228181428_DateTimeOffsetToDateTime.Designer.cs, src/Service/Migrations/Mssql/20240228181428_DateTimeOffsetToDateTime.cs, src/Service/Migrations/Sqlite/20240228181418_DateTimeOffsetToDateTime.Designer.cs, src/Service/Migrations/Sqlite/20240228181418_DateTimeOffsetToDateTime.cs, src/Service/Migrations/Sqlite/SqliteContextModelSnapshot.cs, src/Service/Models/DispatchedEmail.cs, src/Service/Storage/Ef/DbGlobalSqliteContext.cs, src/Service/Storage/Ef/EfTenantStorage.cs
N/A
As it turns out, EF Core provider for SQLite does not support `DateTimeOffset` comparisons, so queries like the one below fail:
```csharp
var from = timeProvider.GetUtcNow() - window;
return await db.DispatchedEmails
// CreatedAt is of type DateTimeOffset
.Where(x => x.CreatedAt >= from)
.ToArrayAsync();
```
Interestingly, even though SQLite does not have any native support for dates (no `datetime` or similar column type), EF Core is able to handle the above query just fine when using regular `DateTime` on the CLR type. Why it doesn't work with `DateTimeOffest` is a mystery.
While you can provide a custom `ValueConverter` and `ValueComparer` inside `OnModelCreating`, this doesn't ultimately help with `>`/`<` comparisons that's used in the query above. …
=> Switch from `DateTimeOffest` to `DateTime` in EF models

.github/workflows/main.yml
Currently, the job runs on all environments and just selectively skips the deployment step if the trigger event is not applicable (e.g. `push` for `prod` instead of `release`). This is fine, but it results in all instances of the `deploy` job marked as having completed, even if they didn't actually do anything.
As a workaround, I've changed the matrix to include an `is-release` parameter. It will be applied to all matrix cases like shown below.
- Workflow triggered by a release event:
- Generated matrix:
- `environment: devtest` / `is-release: true`
- `environment: qa` / `is-release: true`
- `environment: prod` / `is-release: true`
- Exclusion on `is-release: false` does not apply since all cases are `true`
- Final matrix is the same as the generated matrix
- Deployment will happen to all …
=> Dynamic matrix cases for the `deploy` job

src/Api/Endpoints/Authenticators.cs, src/Common/EventLog/Enums/EventType.cs, src/Service/EventLog/Loggers/IEventLogger.cs
- Closes [PAS-379](https://bitwarden.atlassian.net/browse/PAS-379)
- Changes the wording of whitelist and blacklist to allowlist and blocklist respectively.
n/a
n/a
[PAS-379]: https://bitwarden.atlassian.net/browse/PAS-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-379 | Event logging wording allow list & block list

src/AdminConsole/AdminConsole.csproj, src/AdminConsole/Helpers/RazorPageHtmlExtensions.cs, src/AdminConsole/Pages/Shared/_Layout.cshtml
- Related [PAS-382](https://bitwarden.atlassian.net/browse/PAS-382)
We can save some resources every request by moving the correct vue.js dependency into the static web assets folder.
It also fixes a bug where Vue.js wasn't properly being imported with the importmaps `es-shim-module`.
Error 1:
`An import map is added after module script load was triggered.`
Error 2:
`(3) profile:1 Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".`
We can save some resources every request by moving the correct vue.js dependency into the static web assets folder. When building in debug mode, it makes sense to use the debuggable library. Otherwise use the minified production one.
We could consider getting rid of import maps to …
=> PAS-382 | Refactor import maps

src/AdminConsole/Components/Shared/Credentials.razor, src/AdminConsole/Components/Shared/Credentials.razor.cs, src/AdminConsole/Pages/Account/Profile.cshtml, src/AdminConsole/Pages/Account/Profile.cshtml.cs, src/AdminConsole/Pages/Account/UserOnboarding.cshtml, src/AdminConsole/Pages/Account/UserOnboarding.cshtml.cs, src/AdminConsole/Pages/App/Credentials/User.cshtml, src/AdminConsole/Pages/App/Credentials/User.cshtml.cs
- Closes [PAS-384](https://bitwarden.atlassian.net/browse/PAS-384)
We were unable to delete passkeys on the profile page, because it was trying to use the `IScopedPasswordlessClient`. We're now injecting the `IPasswordlessClient` or its derivative `IScopedPasswordlessClient` using the `PasswordlessClient` parameter on the`Credentials.razor` component. A second parameter was then created to pass the `UserId`.
Similarly the user is passed from the claim, rather than using the expensive `UserManager<ConsoleAdmin>` calling the database with an additional trip. The credentials for a user in a given app for a customer are passed using a query parameter `userId` this behavior was not changed.
See above.
n/a
I did the following …
=> PAS-384 | Fix delete passkey bug once and for all

src/Common/Background/BasePeriodicBackgroundService.cs, src/Service/EventLog/EventDeletionBackgroundWorker.cs
Run the `EventDeletionBackgroundWorker` at a fixed time. So we can control when they run.
n/a
n/a
=> Run `EventDeletionBackgroundWorker` at fixed time.

src/AdminConsole/Components/Pages/App/Settings/ManageAuthenticators.razor, src/AdminConsole/Components/Shared/Icons/Fido2AuthenticatorIcon.razor, src/Common/Models/MDS/EntryResponse.cs
- Closes [PAS-262](https://bitwarden.atlassian.net/browse/PAS-262)
- Some authenticators do not have an icon in the MDS. Render a basic icon.
- Format all aaguids so they have the same length to make it more presentable.
n/a
[PAS-262]: https://bitwarden.atlassian.net/browse/PAS-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-262 | Icon for authenticators without icon in MDS

src/AdminConsole/Services/DataService.cs
Use `ExecuteDeleteAsync` to delete an organization rather than attempting to retrieve the organization.
=> Use `ExecuteDeleteAsync` to delete an organization.

src/AdminConsole/Components/Pages/App/ReportingComponents/TotalCredentialsCountChart.razor, src/AdminConsole/Components/Pages/App/ReportingComponents/TotalUsersCountChart.razor, src/AdminConsole/Components/Shared/ApexCharts/Models/Chart.cs, src/AdminConsole/Components/Shared/ApexCharts/Models/Export.cs, src/AdminConsole/Components/Shared/ApexCharts/Models/Toolbar.cs
- Closes [PAS-330](https://bitwarden.atlassian.net/browse/PAS-330)
Presently, when files are being exported, the filenames are essentially 8 random alphanumeric characters followed by their file extension: `fsdhsdfi.csv`, `fsdhsdfi.png`, `fsdhsdfi.svg`. This pull request sets the id of the chart, eg `total-users-count-chart` as the file name. Resulting in the following file names:
- `total-users-count-chart.csv`,
- `total-users-count-chart.png`,
- `total-users-count-chart.svg`
n/a
n/a
[PAS-330]: https://bitwarden.atlassian.net/browse/PAS-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> PAS-330 | Charts: Filenames for export

src/Service/Storage/Ef/DbGlobalContext.cs, src/Service/Storage/Ef/ValueComparers/ArrayValueComparer.cs, src/Service/Storage/Ef/ValueComparers/NullableArrayValueComparer.cs, tests/Service.Tests/Storage/Ef/ValueComparers/ArrayValueComparerTests.cs, tests/Service.Tests/Storage/Ef/ValueComparers/NullableArrayValueComparerTests.cs
n/a
We are currently converting text fields into arrays with Entity Framework, but we are not implementing value comparers. This could impact change tracking: https://learn.microsoft.com/en-us/ef/core/modeling/value-comparers?tabs=ef5
n/a
=> Implement value comparers for the array conversions

src/AdminConsole/datadog.json
We need to track the `Client-Version` header for our front-end facing SDKs.
n/a
n/a
=> Track `Client-Version` header

src/Service/MagicLinks/MagicLinkService.cs, src/Service/SharedManagementService.cs, tests/Api.IntegrationTests/Endpoints/Magic/MagicTests.cs, tests/Api.IntegrationTests/Helpers/App/CreateAppHelpers.cs
N/A
Previously, the monthly quotas were set either when the application changed billing tiers or during the initial migration. New applications created after the initial migrations did not have the correct quota set.
N/A
N/A
- Updated tests
- N/A
=> Fix monthly quotas not applied directly on app creation

src/AdminConsole/EventLog/EventDeletionBackgroundWorker.cs, src/AdminConsole/EventLog/Loggers/InternalEventStorage.cs
Currently, the background services run at random times during the day depending on when the server has last restarted. This pull request makes that `organization delete background worker` runs at a fixed time during the day, 'midnight UTC'.
It will also return the amount of deleted records, for use with logging.
=> Delete expired organization events at midnight UTC.

src/AdminConsole/Pages/Organization/CreateApplication.cshtml
- Closes [PAS-393](https://bitwarden.atlassian.net/browse/PAS-393)
Before, the Api was returning a 409 when there was already an app with the same appid registered. However, the AdminConsole was returning a 500 status code in the front-end.
This was eventually resolved to always return a 200 status code with the body below:
`{ "available": true }`
What we forgot to fix at the time was the Javascript portion which was just checking whether the received response was successful, i.e. `2xx`.
This pull request makes sure we're reading the received body and act upon the value of the received property accordingly.
- Testing changes in admin console.
I did the following to ensure that my changes do not introduce security …
=> PAS-393 | AppId availability check is not displayed in the UI correctly

src/AdminConsole/Components/Pages/Initialize.razor
- Closes [PAS-375](https://bitwarden.atlassian.net/browse/PAS-375)
Forgot to set the default quota for admin console.
Added the default value in the code.
- Manually testing through self hosting. Can initialize AdminConsole
[PAS-375]: https://bitwarden.atlassian.net/browse/PAS-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Initialize AC Quota

src/Service/MagicLinks/MagicLinkService.cs
- Closes [PAS-375](https://bitwarden.atlassian.net/browse/PAS-375)
AdminConsole is being restricted by how recently it was created in new self hosted instances. This checks if the requesting application is admin console by tenant name.
Adds an `IsAdminConsole` check when enforcing the 24h limit quota.
- ran unit tests.
- ensured quota enforcement was kept in place.
[PAS-375]: https://bitwarden.atlassian.net/browse/PAS-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow AC to send magic links

Api.dockerfile
The alpine image is missing `libsodium`, causing unit & integration tests to fail.
```
[06:19:42 INF] HTTP POST /admin/apps/app84c66feff0c44cc2bbc5199c1615f259/create responded 200 in 18.2468 ms
fail: Passwordless.Api.Helpers.LoggingMiddleware[10000]
The API has encountered an error
System.PlatformNotSupportedException: Could not initialize platform-specific components. NSec may not be supported on this platform. See https://nsec.rocks/docs/install for more information.
---> System.DllNotFoundException: Unable to load shared library 'libsodium' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
Error loading shared library ld-linux-aarch64.so.1: No such file …
```
=> `libsodium` is missing in the alpine test image.

src/Api/Endpoints/Magic.cs, src/Common/MagicLinks/Models/SendMagicLinkRequest.cs, src/Service/Models/SigninTokenRequest.cs
- Closes [PAS-373](https://bitwarden.atlassian.net/browse/PAS-373)
Currently there is no restriction for TTL with both MGATs and Magic Links. This adds range of valid values of 1 second to 7 days.
Adds min value of 1 second and max value of 7 days to Magic Links and MGATs via the RangeValidationAttribute.
- Ran tests
- changes were limited to adding validation to request models.
[PAS-373]: https://bitwarden.atlassian.net/browse/PAS-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add range to TTL

src/AdminConsole/Billing/BackgroundServices/StripeConfigurationUpdaterBackgroundService.cs, src/AdminConsole/Billing/BillingBootstrap.cs, src/AdminConsole/Pages/Billing/webhook.cshtml.cs
This pull request allows that Stripe API secrets are updated automatically without having to restart the Passwordless.dev admin console in production. Effectively reducing down-time.
The Stripe .NET SDK unfortunately does not support the options pattern.
The background service remains active during the entire application life cycle until it shuts down.
n/a
- Tested for Self-hosting
- Tested for Cloud
- __
=> Hotswap Stripe API secrets when they are updated.

src/Api/Reporting/Background/ActiveUserReportingBackgroundService.cs, src/Api/Reporting/Background/UsersCountReportingBackgroundService.cs, src/Service/Storage/Ef/EfGlobalGlobalStorage.cs
n/a
When we have multiple instances running. It's executed multiple times around the same time. This prevents an exception/error from being logged. Changing the logging level to warning as it was caught.
In an ideal situation, we'd have only one master service to sync or multiple with each syncing a subset/partition.
=> Handle DbConcurrencyException for reporting.

src/Api/datadog.json
Allows us to track the `Client-Version` header in Datadog. Relevant for when errors happen due to a specific Android or JS SDK.
n/a
n/a
- __
- __
=> Track the `Client-Version` header in the API.

src/Api/Endpoints/Alias.cs, src/Api/Endpoints/Apps.cs, src/Api/Endpoints/Authenticators.cs, src/Api/Endpoints/Credentials.cs, src/Api/Endpoints/Events.cs, src/Api/Endpoints/Magic.cs, src/Api/Endpoints/Register.cs, src/Api/Endpoints/Reporting.cs, src/Api/Endpoints/Signin.cs, src/Api/Endpoints/Users.cs, src/Api/Program.cs, src/Api/wwwroot/openapi.css, src/Common/Models/Authenticators/ConfiguredAuthenticatorRequest.cs
- Add response types for every endpoint
- Remove list of schemas at the bottom, which is now completely redundant given they're present on the endpoints themselves.
- Rename schema definition from v1 to v4.
- Apply CORS policy to the schema at /swagger/v4/swagger.json so we can use the schema with VuePress.
- Fix where `GET /authenticators/list` applies many ApiSecret headers to the schema.
- CSS cleanup
n/a
- __
- __
=> PAS-202 | OpenAPI improvements

src/Api/Endpoints/Signin.cs
Copied from Passwordless .NET SDK
n/a
n/a
- __
- __
=> PAS-202 | Add missing description for generating an authentication token

src/AdminConsole/Pages/Organization/Overview.cshtml, src/AdminConsole/Pages/Organization/Overview.cshtml.cs
The navigation is broken clicking one of the application cards. That is because the credentials list is not a Razor Page.
n/a
- __
- __
=> Fix navigation on /Organization/Overview

src/AdminConsole/Components/App.razor
- Closes [PAS-412](https://bitwarden.atlassian.net/browse/PAS-412)
- Closes [PAS-413](https://bitwarden.atlassian.net/browse/PAS-413)
Some elements to not seem to be initialized properly when the page loads, this is caused by Blazor's enhanced navigation feature which is enabled by default.
n/a
n/a
- __
- __
[PAS-412]: https://bitwarden.atlassian.net/browse/PAS-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PAS-413]: https://bitwarden.atlassian.net/browse/PAS-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-412 & PAS-413 | Disable enhanced navigation globally

src/AdminConsole/HealthChecks/HealthCheckBootstrap.cs, src/AdminConsole/Program.cs, src/Api/HealthChecks/HealthCheckBootstrap.cs, src/Api/Program.cs, src/Common/HealthChecks/HealthCheckEndpoints.cs
Using constants for health check endpoints
Allows the strings to be interned and allocated once in memory. Should improve memory allocation for middleware operations.
n/a
- __
- __
=> string interning for health check endpoints

src/AdminConsole/Styles/tailwind.css
- Closes [PAS-418](https://bitwarden.atlassian.net/browse/PAS-418)
I had overwritten the default style for lists. Which didn't have discs by default, instead had 'none'. This reverts the change and only applies the bullet points to the validation-errors.
n/a
- __
- __
[PAS-418]: https://bitwarden.atlassian.net/browse/PAS-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-418 | Fix bullet points showing up for lists where it's not supposed to.

global.json
- Closes [PAS-419](https://bitwarden.atlassian.net/browse/PAS-419)
In .NET 8.0.2 and lower, `NavigationManager.Refresh()` was not working properly for Blazor applications that are statically rendered. This is fixed in `8.0.203` and higher.
It is important to avoid touching the rule below in`.editorconfig` as otherwise `dotnet format` would be broken.
`dotnet_diagnostic.IDE0005.severity = silent`
n/a
n/a
- __
- __
[PAS-419]: https://bitwarden.atlassian.net/browse/PAS-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-419 | < .NET 8.0.203 don't support NavigationManager.Refresh()

src/AdminConsole/Components/Pages/Organization/Admins.razor.cs, src/AdminConsole/Components/Shared/NavigationManagerExtensions.cs
- Closes [PAS-419](https://bitwarden.atlassian.net/browse/PAS-419)
A .NET runtime bug with relation to `NavigationManager.Refresh()` is causing the `Admins` page to crash under certain circumstances when refreshing the page.
After investigation, I found that the .NET runtime in 'QA', 'Staging' and 'Production is using `.NET Runtime 8.0.101`.
Until Microsoft upgrades the runtimes of Azure Web Applications in Azure, this pull request provides backwards compatibility.
Update (April 15, 2024): Received response from Microsoft `Following discussions with our internal team about the availability of the latest .NET8 SDK and runtime for your app services, I'd like to inform you that the deployment to update to the latest .NET8 SDK and runtime is scheduled to begin in May and will be completed by …
=> PAS-419 | Provide backwards compatibility for .NET 8.0.1 runtime and lower

src/AdminConsole/Services/InvitationService.cs
- Closes [PAS-433](https://bitwarden.atlassian.net/browse/PAS-433)
We were previously using Razor's ActionContext and UriHelper to build the invite link sent to invited admins. The page was migrated to blazor and the uri manually constructed.  This keeps the InvitationService ignorant of where its being called from.  However, the UrlHelper previously escaped the uri being built.  This PR adds that escaping back in for the invite code.
This uses `Uri.EscapeDataString(...)` on the generate code for the invite.
- Manual testing of invites to ensure special characters were encoded correctly.
- N/A
[PAS-433]: …
=> PAS433 Fix invite link

src/Service/MagicLinks/MagicLinkService.cs, tests/Api.IntegrationTests/Endpoints/Magic/MagicTests.cs
Configuration option: `MagicLinks.NewAccountTimeout`. uses the standard .NET `TimeSpan` format, e.g. `17:00:00` (17 hours) or `1.16:00:00` (1 day and 16 hours). Defaults to 24 hours if not set.
=> Make the magic link timeout for newly created accounts configurable

src/Common/HealthChecks/VersionHealthCheck.cs
Return the .NET runtime version at least for the time being. This can help us diagnose specific bugs that we've experienced in the past few weeks in relation to Blazor. You can obtain the dotnet runtime version for an Azure Web App, but you require write access.
n/a
```
{
"status": "Healthy",
"elapsedMilliseconds": 3.8932,
"results": {
"version": {
"status": "Healthy",
"elapsedMilliseconds": 0.8903,
"data": {
"version": "1.0.0+476e82a3acc6e7549b7c450bfe4d8d3a2d4ab9a0",
"net-runtime": ".NET 8.0.4"
}
}
}
}
```
- See screenshots
- Exposing the .NET runtime could be a potential vulnerability. However, when publishing images, we'd …
=> Return .NET runtime version

src/AdminConsole/Pages/App/Settings/Settings.cshtml, src/AdminConsole/Pages/App/Settings/Settings.cshtml.cs, src/AdminConsole/Services/ApplicationService.cs, src/AdminConsole/Services/IApplicationService.cs, src/AdminConsole/Services/PasswordlessManagement/IPasswordlessManagementClient.cs, src/AdminConsole/Services/PasswordlessManagement/PasswordlessManagementClient.cs, src/Api/Endpoints/Apps.cs, src/Service/SharedManagementService.cs, tests/Service.Tests/Implementations/SharedManagementServiceTests.cs
- Closes [PAS-417](https://bitwarden.atlassian.net/browse/PAS-417)
This simplifies the informational burden on the "delete" section of the application settings page. Instead of outlining all possible scenarios (which are kind of hard to understand because we have several conditions for whether an app can be deleted immediately), the page will now only show the information relevant to the specific app the user is attempting to delete.
- When the settings page is loaded, AC queries the API to check if the app can be deleted immediately
- To do that, a new endpoint `{app-id}/can-delete-immediately` was added, which returns JSON-encoded `bool`
App has no users OR has been created <3 days ago:
App has users AND has been created >=3 days ago:
I did the following to ensure that my changes were …
=> PAS-417 | Improve UX when deleting application

src/AdminConsole/Components/Pages/App/Onboarding/GetStarted.razor, src/AdminConsole/Components/Pages/App/Onboarding/GetStarted.razor.cs
- Closes [PAS-434](https://bitwarden.atlassian.net/browse/PAS-434)
Changes "private key" to "secret key" in the "get started" section of the Admin Console to avoid confusion
[PAS-434]: https://bitwarden.atlassian.net/browse/PAS-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-434 | change private key wording to secret key in AC

src/AdminConsole/Components/Pages/App/Reporting.razor, src/AdminConsole/Components/Shared/Stats/TrendingCardsStats.razor, tests/AdminConsole.Tests/Components/Shared/Stats/TrendingCardsStatsTests.cs
- Closes [PAS-448](https://bitwarden.atlassian.net/browse/PAS-448)
* adds `<Panel>` container to the top two modules in the reports page so that they match the module with the graphs
* fixes an issue i saw in top modules where "NaN of total" will show with a new org that doesn't have any users yet
| Before    | After |
| -------- | ------- |
| <img width="1694" alt="Screenshot 2024-05-09 at 11 23 16 AM" src="https://github.com/bitwarden/passwordless-server/assets/14082576/7e2c95a3-489d-4384-b5ac-f27878a1262b">  | <img width="1703" alt="Screenshot 2024-05-09 at 11 25 26 AM" src="https://github.com/bitwarden/passwordless-server/assets/14082576/00dacd1b-05c0-48f4-aca5-be99eabb8ae5"> |
| <img width="418" alt="Screenshot 2024-05-09 at 11 24 06 AM" …
=> PAS-448 | update module style in reports

src/AdminConsole/Billing/BackgroundServices/MeteredBillingBackgroundService.cs, src/AdminConsole/Billing/NoOpBillingService.cs, src/AdminConsole/Services/BaseBillingService.cs, src/AdminConsole/Services/ISharedBillingService.cs, src/AdminConsole/Services/SharedStripeBillingService.cs
- Closes [PAS-444](https://bitwarden.atlassian.net/browse/PAS-444)
This is the first step to populate metered billing from periodic credential reports in the api. Stripe recommends we keep the usage records ourselves, so for this the periodic credential reports will serve their purpose.
In step 2 of the refactoring, we will stop updating the CurrentUserCount in the Applications table periodically, but instead do it upon login of an admin to significantly reduce network traffic.
For testing I populated PeriodicCredentialReports first. Then forced the background job to run:
- Tested locally.
- __
[PAS-444]: …
=> PAS-444 | Populate metered billing from periodic credential reports.

src/AdminConsole/Endpoints/ApplicationEndpoints.cs
- Closes [PAS-434](https://bitwarden.atlassian.net/browse/PAS-434)
Continuation of https://github.com/bitwarden/passwordless-server/pull/580/files
QA thought we should also update the wording when you download the keys 
[PAS-434]: https://bitwarden.atlassian.net/browse/PAS-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-434 | update secret api key wording when you download them

.github/renovate.json, global.json
n/a
- Do not roll forward to the latest minor .NET SDK to avoid unexpected behavior.
- Renovate should not suggest to update the `global.json`.
- __
- __
=> Exclude .NET SDK from being upgraded with Renovate

src/Api/Program.cs, src/Service/SharedManagementService.cs, tests/Service.Tests/Implementations/SharedManagementServiceTests.cs
Can potentially save a little bit of memory by injecting it request scoped instead of transient. `ITenantStorage` was also nowhere being referenced any longer.
- Verified everything was working properly.
- Integration tests executed.
- __
=> Inject `ISharedManagementService` request scoped instead of transient.

self-host/entrypoint.sh
- Closes [PAS-455](https://bitwarden.atlassian.net/browse/PAS-455)
Disables the magic links quota enforcement in a self-hosted environment, so that customers that spin up new instances can create new applications that are not the same as the admin e-mail that was used to setup Passwordless.dev for the first time.
When a new self-hosted instance is being spun up, you're being asked to enter your name and e-mail for the administrator account managing the Passwordless.dev self-hosted instance. But e-mails can only be sent out to the admin e-mails contained in the `adminconsole` application.
If you then want to create a new organization using a different e-mail address than the one mentioned above, you cannot do so as there was a 24h period which only allows the initial admin to receive magic …
=> PAS-455 | Fix magic links for self-hosted instances

src/AdminConsole/Components/App.razor
- Closes [PAS-397](https://bitwarden.atlassian.net/browse/PAS-397)
Corrects the path for the passwordless client lib on blazor pages.
Remvoes the `~` from the `SecureScript` path when adding the passwordless client lib. Otherwise it returned a 404.
- Visited razor pages, blazor components in razor pages, and blazor pages to validate errors weren't thrown in console.
[PAS-397]: https://bitwarden.atlassian.net/browse/PAS-397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix-razor-path-for-client-js

src/AdminConsole/Components/Pages/App/Settings/AuthenticationConfiguration/AuthenticationConfigurationFormModel.cs, src/Common/Models/Apps/SetAuthenticationConfigurationRequest.cs
- Closes [PAS-504](https://bitwarden.atlassian.net/browse/PAS-504)
`.` was not working for auth config name, so removed it from allowed characters.
Removed `.` from allowed characters.
- Manual test. Validation now fails with `.` in purpose.
[PAS-504]: https://bitwarden.atlassian.net/browse/PAS-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Removed `.` from allowed characters

src/AdminConsole/Pages/App/Playground/Client.cshtml, src/Service/Models/SignInBeginDTO.cs
- Closes [PAS-512](https://bitwarden.atlassian.net/browse/PAS-512)
Fixed setting the alias to be used by the client in the playground. Fixed the purpose being passed to step up to use value instead of the raw ref.
Copy paste error resulting in an undefined alias and purpose not being set.
- verified i could register, sign in and step up with an alias in the playground
- __
[PAS-512]: https://bitwarden.atlassian.net/browse/PAS-512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> pas512-fix-playground-client

src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/AuthenticationConfiguration.razor
- Closes [PAS-532](https://bitwarden.atlassian.net/browse/PAS-532)
When failing to pull the auth configs, it errored and failed to load the page. This will put a try catch that will log the error and return an empty array on failure.
Added a try catch around getting the auth configs.
- Able to get auth configs without an issue
- No new paths added
[PAS-532]: https://bitwarden.atlassian.net/browse/PAS-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-532-better-error-handling-auth-configs

src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/FeatureListItemIcon.razor, src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/PlanSection.razor, src/AdminConsole/Middleware/CurrentContext.cs, src/AdminConsole/Middleware/ICurrentContext.cs, src/AdminConsole/Pages/App/Settings/Settings.cshtml, src/AdminConsole/Pages/App/Settings/Settings.cshtml.cs
- Closes [PAS-479](https://bitwarden.atlassian.net/browse/PAS-479)
When API keys or API secrets are locked or unlocked, the plan section fails to initialize and fails to render as a result. This pull request will repair the lifecycle indefinitely as more sections & forms are added to the application settings pages.
https://github.com/user-attachments/assets/13567947-4a78-4718-921b-8d66e7430a38
- __
- __
[PAS-479]: https://bitwarden.atlassian.net/browse/PAS-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-479 | Repair plan section lifecycle when api keys are (un)locked

src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/MagicLinksSection.razor, src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/MagicLinksSection.razor.cs, src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/ManuallyGeneratedAuthenticationTokensSection.razor, src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/ManuallyGeneratedAuthenticationTokensSection.razor.cs, src/AdminConsole/Pages/App/Settings/Settings.cshtml, src/AdminConsole/Pages/App/Settings/Settings.cshtml.cs
- Closes [PAS-479](https://bitwarden.atlassian.net/browse/PAS-479)
Magic links section was broken when unlocking/locking API keys.
- __
- __
[PAS-479]: https://bitwarden.atlassian.net/browse/PAS-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-479 | Fix magic links section lifecycle when locking/unlocking API keys

src/Service/Migrations/Mssql/20240709134147_AddIndicesForHotCodePaths.Designer.cs, src/Service/Migrations/Mssql/20240709134147_AddIndicesForHotCodePaths.cs, src/Service/Migrations/Sqlite/20240709134121_AddIndicesForHotCodePaths.Designer.cs, src/Service/Migrations/Sqlite/20240709134121_AddIndicesForHotCodePaths.cs, src/Service/Migrations/Sqlite/SqliteContextModelSnapshot.cs, src/Service/Storage/Ef/DbGlobalContext.cs
- Closes [PAS-516](https://bitwarden.atlassian.net/browse/PAS-516)
This pull request covers the indices for the hot code paths such as:
- Private key and public key validation of incoming requests
- Registration of passkeys
- Signing in with and without aliases
- Enumerating credentials
n/a
n/a
- __
- __
[PAS-516]: https://bitwarden.atlassian.net/browse/PAS-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-516 | Verified indices for ApiKeys, Aliases, Credentials

src/Api/Endpoints/AuthenticationConfiguration.cs, src/Api/Endpoints/Signin.cs
ApiKey and ApiSecret fields had 2 to more entries when viewing the API documentation at `/swagger/index.html`.
Removed `.WithOpenApi()` from grouped endpoint builders, and moved it to individually to prevent the same bug happening.
- __
- __
=> Fix Open API documentation spawning multiple ApiKey/ApiSecret fields

src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/DeleteApplicationSection.razor, src/AdminConsole/Components/Pages/App/Settings/SettingsComponents/DeleteApplicationSection.razor.cs, tests/AdminConsole.Tests/Components/Pages/App/Settings/SettingsComponents/DeleteApplicationSectionTests.cs
- Closes [PAS-544](https://bitwarden.atlassian.net/browse/PAS-544)
- Shows expected copy/text depending on application state.
- Does not throw exception anymore when submitting the forms.
- __
- __
[PAS-544]: https://bitwarden.atlassian.net/browse/PAS-544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-544 | Defect when a user cannot immediately delete their application expected copy is not shown

src/AdminConsole/Components/Pages/Organization/SettingsComponents/DeleteOrganizationComponent.razor, tests/AdminConsole.Tests/Components/Pages/Organization/Settings/SettingsComponents/DeleteOrganizationComponentTests.cs, tests/AdminConsole.Tests/Factory/ClaimsPrincipalFactory.cs
Unit tests for the `DeleteOrganizationComponent`. No changes otherwise.
- Verifies validation.
- Verifies that e-mails are sent.
- Verifies existing subscriptions are canceled when appropriate.
- Verifies the user is logged out after their organization is deleted.
- __
- __
=> `DeleteOrganizationComponent` unit tests

src/AdminConsole/Billing/BackgroundServices/UserCountUpdaterBackgroundService.cs, src/AdminConsole/Billing/BillingBootstrap.cs
- Closes [PAS-552](https://bitwarden.atlassian.net/browse/PAS-552)
Restore `UserCountUpdaterBackgroundService` for use in internal reporting at Bitwarden which happens bi-weekly. This service was initially dropped due to performance reasons.
- __
- __
[PAS-552]: https://bitwarden.atlassian.net/browse/PAS-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-552 | Restore BackgroundService for Bitwarden's internal reporting

src/AdminConsole/Program.cs, src/AdminConsole/Services/IPostSignInHandlerService.cs, src/AdminConsole/Services/PostSignInHandlerService.cs
- Closes [PAS-552](https://bitwarden.atlassian.net/browse/PAS-552)
The `CurrentUserCount` was no longer being updated in the `Applications` table of the admin console. This was happening because we listen to the `OnSignedIn` callback, where we are successfully able to listen when an admin signs in and execute custom code to perform certain actions, such as updating and caching the amount of users.
The caching of the amount of users was running on a background job half a year ago which was running every few hours, but was causing an unnecessary amount of network traffic.
We injected an object which is responsible for handling any post signin events, but it turns out the `ClaimsPrincipal` is not signed in inside this handler, although the `ClaimsPrincipal is signed in inside the …
=> PAS-552 | CurrentUserCount no longer updating

src/AdminConsole/Authorization/CustomClaimTypes.cs, src/AdminConsole/Authorization/HasAppHandler.cs, src/AdminConsole/Services/CustomUserClaimsPrincipalFactory.cs
- Closes [PAS-554](https://bitwarden.atlassian.net/browse/PAS-554)
When an admin signs in, all the applications belonging to the organization are added to the claims/token. When an application is added in a different session, you will get an access denied message in your old session, because it doesn't know the application was created for your organization.
Under very particular circumstances, where all the stars would have to align (never happens), you could theoretically access an application of a different organization. Although the impact would be fairly small as that application would have to be newly created by the new organization, and deleted by the old one in quick succession.
- __
I did the following to ensure …
=> PAS-554 | Fix Access Denied creating application in different session

src/AdminConsole/Authorization/HasAppHandler.cs, src/AdminConsole/Components/Layouts/ApplicationNavMenu.razor, src/AdminConsole/Components/Pages/Organization/Create.razor, src/AdminConsole/Middleware/CurrentContextMiddleware.cs, src/AdminConsole/Program.cs, src/AdminConsole/Services/DataService.cs, src/AdminConsole/Services/OrganizationFeatureService.cs, tests/AdminConsole.Tests/Components/Pages/App/BaseApplicationPageTests.cs, tests/AdminConsole.Tests/Components/Shared/Layouts/ApplicationNavMenuTests.cs
- Closes [PAS-559](https://bitwarden.atlassian.net/browse/PAS-559)
1. We will need IDbContextFactory, this won't fix it permanently. Authorization handlers can be executed concurrently when Blazor/Razor components are being rendered.
2. Adds the alias route '/signup' back for '/organization/create'
n/a
- __
- __
[PAS-559]: https://bitwarden.atlassian.net/browse/PAS-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-559 | Authorization handler is being executed concurrently.

src/AdminConsole/Components/Pages/App/Settings/AuthenticationConfiguration/AuthenticationConfigurationForm.razor, src/AdminConsole/Program.cs, src/AdminConsole/Services/ProblemDetailsDelegatingHandler.cs
- Closes [PAS-557](https://bitwarden.atlassian.net/browse/PAS-557)
It is now properly showing the error message when an error is being returned by the Passwordless.dev back-end.
- __
- __
[PAS-557]: https://bitwarden.atlassian.net/browse/PAS-557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-557 | Show error message when adding duplicate auth config

src/AdminConsole/AdminConsole.csproj, src/AdminConsole/Pages/App/Playground/NewAccount.cshtml, src/AdminConsole/Pages/App/Playground/NewAccount.cshtml.cs, src/Service/Fido2Service.cs, src/Service/Models/RegisterToken.cs, src/Service/TokenService.cs, tests/Service.Tests/Implementations/Fido2ServiceTests.cs
- Closes https://bitwarden.atlassian.net/browse/PAS-556
This adds an ability to provide credential hints to the `/register` endpoint.
- I used the Playground to verify that setting different hints results in different behavior
- __
=> PAS-556 | Add support for credential hints to the register flow

src/AdminConsole/Pages/App/Playground/NewAccount.cshtml.cs
- Closes [PAS-560](https://bitwarden.atlassian.net/browse/PAS-560)
`Hints` field is null, causing it to crash on the line where it tries to split the string by comma separated values.
- __
- __
[PAS-560]: https://bitwarden.atlassian.net/browse/PAS-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-560 | Playground crashing w/ new user without 'Hints' field

src/AdminConsole/Components/Shared/SecureImportMapScript.razor, src/AdminConsole/Components/Shared/SecureImportMapScript.razor.cs
- Closes [PAS-380](https://bitwarden.atlassian.net/browse/PAS-380)
The version query parameter was being rendered repeatedly, causing the Vue dependency not to be found. Possibly this could have had an impact on other inline rendered scripts, even if they don't rely on Vue.
- __
- __
[PAS-380]: https://bitwarden.atlassian.net/browse/PAS-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-380 | Bug where version query parameter gets rendered repeatedly.

tests/Api.IntegrationTests/ApiCollectionFixture.cs, tests/Api.IntegrationTests/AuthorizationTests.cs, tests/Api.IntegrationTests/Endpoints/App/AppTests.cs, tests/Api.IntegrationTests/Endpoints/AuthenticationConfiguration/AuthenticationConfigurationTests.cs, tests/Api.IntegrationTests/Endpoints/Authenticators/AuthenticatorsTests.cs, tests/Api.IntegrationTests/Endpoints/Credentials/CredentialsTests.cs, tests/Api.IntegrationTests/Endpoints/Events/EventsTests.cs, tests/Api.IntegrationTests/Endpoints/Magic/MagicTests.cs, tests/Api.IntegrationTests/Endpoints/Register/RegisterAttestationTests.cs, tests/Api.IntegrationTests/Endpoints/Register/RegisterTests.cs, tests/Api.IntegrationTests/Endpoints/Register/RegisterTokenTests.cs, tests/Api.IntegrationTests/Endpoints/SignIn/SignInTests.cs, tests/Api.IntegrationTests/Middleware/AuthorizationIntegrationTests.cs, tests/Api.IntegrationTests/Middleware/RoutingIntegrationTests.cs, tests/Api.IntegrationTests/PasswordlessApiFixture.cs
Significantly reduces the resources required to run the integration tests as it reuses the Microsoft SQL Server test container.
If the tests are properly written, we should not see any issues. In case we do need a unique instance, we can just use a different collection identifier.
- __
- __
=> Improve integration tests performance

tests/Api.IntegrationTests/PasswordlessApiFixture.cs
After upgrading to Docker 4.33, I cannot get the integration tests to work on either Windows or Mac OS. This appears to work on both. There are some posts mentioning that the way we need to check for a ready SQL Server container has changed recently:
- https://github.com/testcontainers/testcontainers-dotnet/issues/1220
Confirmed to work on:
- MacOS w/ Docker 4.32
- MacOS w/ Docker 4.33
- Windows 11 w/ Docker 4.33.1
Not working on:
- Windows 11 w/ Docker 4.32
- __
- __
=> Wait Strategy needs to be changed for TestContainers

src/Api/Email/DispatchedEmailCleanupService.cs
=> Missing dispose

src/Api/Middleware/PathValidation.cs, src/Api/Program.cs
The middleware shouldn't be executing on undefined endpoints, given there's nothing to log.
- __
- __
=> Do not execute event logging middleware on undefined endpoints

src/AdminConsole/Pages/App/Playground/NewAccount.cshtml, src/AdminConsole/Pages/App/Playground/NewAccount.cshtml.cs
Part of PAS-472
Since we're sending the form data using Vue and completely bypassing Razor Pages request pipeline, the validation attributes are not properly honored. I've added validation for Hints in Vue to avoid vague 400 errors on invalid hints. This is hacky, but a proper solution would require rewriting the page to not use Vue to send the registration request, or have better validation infrastructure on our front-end. I don't think it's worth the effort, given other priorities.
=> Add hacky validation for hints during registration

src/AdminConsole/AdminConsole.csproj
- Closes [PAS-563](https://bitwarden.atlassian.net/browse/PAS-563)
Credential cards show an empty value for RPID while the values are being stored correctly.
- __
- __
[PAS-563]: https://bitwarden.atlassian.net/browse/PAS-563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-563 | RPID is null on credential cards

src/Common/Services/Mail/Smtp/SmtpMailProvider.cs, src/Common/Services/Mail/Smtp/SmtpMailProviderOptions.cs
We do not need to override the sender in the SMTP configuration, as this is being done globally in the `AggregateMailProvider`.
- __
- __
=> Do not override sender for SMTP configuration

src/AdminConsole/Pages/Account/Login.cshtml.cs
When clicking on the logo, it would throw 500 because it couldn't find a Razor page for `/Organization/Overview/`. Changed this to a plain redirect since the overview page was migrated to blazor.
Changes `LocalRedirect` based off Razor Page to be `Redirect`.
- Manually tested clicking the logo and ensured routing worked.
- N/A
=> Fixing routing for when you click on Sidebar logo.

self-host/Dockerfile, self-host/entrypoint.sh
- Closes [PAS-570](https://bitwarden.atlassian.net/browse/PAS-570)
- __
- __
[PAS-570]: https://bitwarden.atlassian.net/browse/PAS-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-570 | Extra colon appended to ApiUrl unnecessarily

Api.dockerfile
- Closes [PAS-572](https://bitwarden.atlassian.net/browse/PAS-572)
- __
- __
[PAS-572]: https://bitwarden.atlassian.net/browse/PAS-572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-572 | Fix mailing on Passwordless Test API image

.github/workflows/docker.yml
- Closes #712 
When we pull Docker images, we would expect to have `latest` always reflect a stable release or production release by default. Now, the latest tag seems to pull any image that is in the main branch or in QA testing.
I've changed the behavior to below, so people can still continue testing the latest `qa` or `dev` build separately. While the latest production release will carry the tags `latest` and `stable` in addition to their respective build numbers.
- `push to main` -> `dev`
- `prerelease release` -> `qa`
- `release` -> `latest` & `stable`
- __
- __
=> Fix the publishing of Docker images

.github/workflows/docker.yml
We should always push a image with the 'qa' tag when a release event happens.
- __
- __
=> Always release image to 'qa' upon release event

src/Service/Models/SigninTokenRequest.cs
This is not an obsolete property as it's actually being used. This will incorrectly hide it from our Open API documentation.
- __
- __
=> #731 | TimeToLive is not an obsolete property

src/Api/Endpoints/AuthenticationConfiguration.cs
- Closes [PAS-584](https://bitwarden.atlassian.net/browse/PAS-584)
The header fields for `ApiSecret` and `ApiKey` are duplicated, this is caused by the `.WithOpenApi()` method being used for these endpoints.
- __
- __
[PAS-584]: https://bitwarden.atlassian.net/browse/PAS-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PAS-584 | Duplicate ApiSecret / ApiKey header fields in swagger

.github/workflows/main.yml
Removes the Codecov token which is no longer needed to upload results.
=> Remove references to Codecov token

.github/workflows/docker.yml, .github/workflows/main.yml
[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Updating to use Azure Key Vault Secrets in place of GitHub secrets.
All GitHub secrets have been migrated to the repository's respective Key Vault.
Azure Service Principals have been updated to use Managed Identities with OIDC.
[BRE-831]: https://bitwarden.atlassian.net/browse/BRE-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BRE-831] migrate secrets AKV

.github/renovate.json, tests/Api.IntegrationTests/Api.IntegrationTests.csproj, tests/Api.Tests/Api.Tests.csproj, tests/Common.Tests/Common.Tests.csproj, tests/Service.Tests/Service.Tests.csproj
- Closes [PAS-592](https://bitwarden.atlassian.net/browse/PAS-592)
Since fluent assertions went with a commercial license, we are going to stay off the license at this point in time.
- ✅  Ran tests
- ✅  No endpoints changed and no known security issues with these versions.
[PAS-592]: https://bitwarden.atlassian.net/browse/PAS-592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PAS-592] - Downgrade FluentAssertions

src/Service/Extensions/Models/AuthenticatorAttestationRawResponseExtensions.cs, src/Service/Fido2Service.cs, src/Service/Models/AuthenticatorAttestationResponseDTO.cs, src/Service/Models/RegistrationCompleteDTO.cs, tests/Api.IntegrationTests/Helpers/BrowserCredentialsHelper.cs
- Closes [PAS-596](https://bitwarden.atlassian.net/browse/PAS-596)
Added wrapper class for AuthenticatorAttestationRawResponse so that we could default the value for Transports.
- __
- __
[PAS-596]: https://bitwarden.atlassian.net/browse/PAS-596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PAS-596] Add wrapper type for AuthenticatorAttestationRawResponse
